"""Add sale price and updated date

Revision ID: 21431dc973cb
Revises: 
Create Date: 2026-06-24 23:28:03.466309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21431dc973cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('sale_price')

    # ### end Alembic commands ###
